import { AppStates } from "@/contexts/States";
import "./globals.css";
import Navbar from "@/components/Navbar.jsx";

export const metadata = {
  title: "WCAG Scan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppStates>
        <body>
          <Navbar />
          {children}
        </body>
      </AppStates>
    </html>
  );
}
